package com.mikront.fillics.resource;

public enum Strings {
    APP_NAME,

    PANEL_REQUEST,
    LABEL_TEACHER,
    LABEL_GROUP,
    LABEL_DATE_FROM,
    LABEL_DATE_TO,
    BUTTON_REQUEST,
    PANEL_TYPES,
    PANEL_SUBJECTS,
    PANEL_GROUPS,
    BUTTON_EXPORT,

    UNKNOWN_TYPE,
    UNKNOWN_GROUP,

    STEP_READY,
    STEP_GETTING_TEACHERS,
    STEP_GETTING_GROUPS,
    STEP_GETTING_SCHEDULE,
    STEP_COMPILING_DATA
}